"""Append the executable tail to a Vellvm test.

Two modes.

1. Print-all (the default).  Tests in the style of tests/ll/aggregate-poison.ll
   define one `i64`-returning function per case, then end with a `main` that
   prints each result (so the file can be run natively and its output diffed
   against clang) and an `ASSERT EQ` per function (for the Vellvm test
   harness).  This mode writes that tail, getting the printf format-string
   array lengths right.

       python3 tests/gen.py BODY.ll SPEC > tests/ll/NAME.ll

   BODY.ll holds the header comment and the test functions.  SPEC has one line
   per test, `<function-name> <expected-i64-result>`, in the order the results
   should be printed, e.g.

       store_byte_constant 42
       bitcast_byte_constant 1000

2. Dispatch (`--dispatch`), for tests where a case may have undefined
   behavior (tests/ub).  Running every case in one process would let the first
   UB mask the rest, so instead each `ASSERT` line becomes case N, and
   `main N` runs case N alone:

       python3 tests/gen.py --dispatch FILE.ll...

   rewrites each FILE.ll in place, replacing any previously generated tail.
   For each assertion `; ASSERT ...: call <ty> @f(<args>)` it emits

       define <ty> @ub_case_N() { %r = call <ty> @f(<args>)  ret <ty> %r }

   (an argument-free entry point, usable with `llubi --entry-function`), and a
   `main(argc, argv)` that prints `case N: start`, calls @ub_case_N, prints
   `case N: returned <v...>` (each scalar component of the result), and
   returns 0.  The tail goes at the end of the file, so the line numbers that
   `ASSERT UB <line>` refers to do not move.
"""
import re
import sys

# ----------------------------------------------------------------- print-all


def tail(tests):
    """tests: list of (fname, expected). Emits the executable main + ASSERTs."""
    out = ["", "; --- executable form: print each result so the file can be run and",
           "; --- its output diffed against clang/llc.", ""]
    for f, _ in tests:
        s = f"{f}() = %lld\\0A\\00"
        n = len(f) + len("() = %lld") + 2
        out.append(f'@fmt_{f} = private unnamed_addr constant [{n} x i8] c"{s}"')
    out += ["", "declare i32 @printf(ptr, ...)", "", "define i32 @main() {"]
    for i, (f, _) in enumerate(tests):
        out.append(f"  %v{i} = call i64 @{f}()")
        out.append(f"  %p{i} = call i32 (ptr, ...) @printf(ptr @fmt_{f}, i64 %v{i})")
    out += ["  ret i32 0", "}", ""]
    w = max(len(str(e)) for _, e in tests)
    for f, e in tests:
        out.append(f"; ASSERT EQ: i64 {str(e).ljust(w)} = call i64 @{f}()")
    return "\n".join(out) + "\n"

# ------------------------------------------------------------------ dispatch

BEGIN = "; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----"
END = "; ---- END executable tail ----"

ASSERT_RE = re.compile(
    r"^[ \t]*;[ \t]*ASSERT[ \t]+(?:"
    r"(?P<eq>EQ)[ \t]*:[ \t]*(?P<expected>.*?)[ \t]*="
    r"|(?P<succ>SUCCEEDS)[ \t]*:"
    r"|(?P<fails>FAILS)[ \t]*:"
    r"|(?P<ub>UB)[ \t]+(?P<ubline>\d+)[ \t]*:)"
    r"[ \t]*call[ \t]+(?P<ty>.*?)[ \t]+@(?P<fn>[-\w.$]+)[ \t]*\((?P<args>.*)\)[ \t]*$")


def parse_asserts(text):
    """The assertions of a test file, in order, as dicts with keys
    kind (EQ/SUCCEEDS/FAILS/UB), line (1-based line of the ASSERT),
    ubline (for UB), expected (for EQ), ty, fn, args, and src (the line)."""
    out = []
    for i, l in enumerate(text.split("\n"), 1):
        m = ASSERT_RE.match(l)
        if not m:
            continue
        kind = "EQ" if m["eq"] else "SUCCEEDS" if m["succ"] else "FAILS" if m["fails"] else "UB"
        out.append(dict(kind=kind, line=i, src=l.strip().lstrip(";").strip(),
                        ubline=int(m["ubline"]) if m["ubline"] else None,
                        expected=m["expected"], ty=m["ty"].strip(),
                        fn=m["fn"], args=m["args"].strip()))
    return out


def parse_type(s):
    """Parse an LLVM first-class type into a tree:
    ('int', n) | ('fp', name) | ('ptr',) | ('vec'|'arr', n, t) | ('struct', [t])."""
    toks = re.findall(r"[{}<>\[\],]|[\w.]+", s)
    pos = 0

    def ty():
        nonlocal pos
        t = toks[pos]
        pos += 1
        if t in ("<", "["):
            n = int(toks[pos])
            assert toks[pos + 1] == "x"
            pos += 2
            et = ty()
            pos += 1  # '>' or ']'
            return ("vec" if t == "<" else "arr", n, et)
        if t == "{":
            fields = []
            while toks[pos] != "}":
                fields.append(ty())
                if toks[pos] == ",":
                    pos += 1
            pos += 1
            return ("struct", fields)
        if re.fullmatch(r"i\d+", t):
            return ("int", int(t[1:]))
        if t in ("half", "float", "double"):
            return ("fp", t)
        if t == "ptr":
            return ("ptr",)
        raise ValueError(f"unsupported type in assertion: {s}")

    t = ty()
    if pos != len(toks):
        raise ValueError(f"trailing tokens in type: {s}")
    return t


def show_type(t):
    k = t[0]
    if k == "int":
        return f"i{t[1]}"
    if k == "fp":
        return t[1]
    if k == "ptr":
        return "ptr"
    if k == "vec":
        return f"<{t[1]} x {show_type(t[2])}>"
    if k == "arr":
        return f"[{t[1]} x {show_type(t[2])}]"
    return "{ " + ", ".join(show_type(f) for f in t[1]) + " }"


def print_value(t, v, fresh, out):
    """Emit instructions printing each scalar component of value v : t."""
    k = t[0]
    if k == "int":
        n = t[1]
        if n < 64:
            w = fresh()
            out.append(f"  {w} = {'zext' if n == 1 else 'sext'} i{n} {v} to i64")
            v = w
        elif n > 64:
            w = fresh()
            out.append(f"  {w} = trunc i{n} {v} to i64")
            v = w
        out.append(f"  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 {v})")
    elif k == "fp":
        if t[1] != "double":
            w = fresh()
            out.append(f"  {w} = fpext {t[1]} {v} to double")
            v = w
        out.append(f"  call i32 (ptr, ...) @printf(ptr @ub_fmt_fp, double {v})")
    elif k == "ptr":
        w = fresh()
        out.append(f"  {w} = ptrtoint ptr {v} to i64")
        out.append(f"  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 {w})")
    elif k == "vec":
        for i in range(t[1]):
            w = fresh()
            out.append(f"  {w} = extractelement {show_type(t)} {v}, i32 {i}")
            print_value(t[2], w, fresh, out)
    else:
        fields = [t[2]] * t[1] if k == "arr" else t[1]
        for i, ft in enumerate(fields):
            w = fresh()
            out.append(f"  {w} = extractvalue {show_type(t)} {v}, {i}")
            print_value(ft, w, fresh, out)


def cstr(s):
    """The type and c"..." initializer of an LLVM string constant for s + NUL."""
    b = s.encode() + b"\0"
    body = "".join(chr(c) if 32 <= c < 127 and chr(c) not in '"\\' else f"\\{c:02X}" for c in b)
    return f'[{len(b)} x i8] c"{body}"'


def dispatch_tail(text):
    asserts = parse_asserts(text)
    out = [BEGIN,
           "; `main N` runs case N alone, so UB in one case cannot mask another;",
           "; @ub_case_N is an argument-free entry point for the same call.",
           ""]
    for n, a in enumerate(asserts):
        out += [f"; case {n} (line {a['line']}): {a['src']}",
                f"define {a['ty']} @ub_case_{n}() {{",
                f"  %r = call {a['ty']} @{a['fn']}({a['args']})",
                f"  ret {a['ty']} %r",
                "}", ""]
    out += [f"@ub_fmt_start = private unnamed_addr constant {cstr('case %d: start' + chr(10))}",
            f"@ub_fmt_ret = private unnamed_addr constant {cstr('case %d: returned')}",
            f"@ub_fmt_int = private unnamed_addr constant {cstr(' %lld')}",
            f"@ub_fmt_fp = private unnamed_addr constant {cstr(' %g')}",
            f"@ub_fmt_nl = private unnamed_addr constant {cstr(chr(10))}",
            ""]
    if not re.search(r"^\s*(declare|define)\b.*@printf\(", text, re.M):
        out.append("declare i32 @printf(ptr, ...)")
    if not re.search(r"^\s*(declare|define)\b.*@atoi\(", text, re.M):
        out.append("declare i32 @atoi(ptr)")
    out += ["",
            "define i32 @main(i32 %argc, ptr %argv) {",
            "entry:",
            "  %has_arg = icmp sge i32 %argc, 2",
            "  br i1 %has_arg, label %dispatch, label %bad",
            "dispatch:",
            "  %arg1_p = getelementptr ptr, ptr %argv, i64 1",
            "  %arg1 = load ptr, ptr %arg1_p",
            "  %n = call i32 @atoi(ptr %arg1)",
            "  switch i32 %n, label %bad ["]
    out += [f"    i32 {n}, label %case{n}" for n in range(len(asserts))]
    out.append("  ]")
    for n, a in enumerate(asserts):
        counter = iter(range(10**6))

        def fresh(n=n, counter=counter):
            return f"%c{n}_{next(counter)}"
        out += [f"case{n}:",
                f"  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 {n})",
                f"  %c{n}_r = call {a['ty']} @ub_case_{n}()",
                f"  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 {n})"]
        print_value(parse_type(a["ty"]), f"%c{n}_r", fresh, out)
        out += ["  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)",
                "  ret i32 0"]
    out += ["bad:", "  ret i32 2", "}", END]
    return "\n".join(out) + "\n"


def strip_tail(text):
    i = text.find(BEGIN)
    return text if i < 0 else text[:i].rstrip("\n") + "\n"


def dispatch(paths):
    for p in paths:
        body = strip_tail(open(p).read())
        open(p, "w").write(body + "\n" + dispatch_tail(body))


if __name__ == "__main__":
    if sys.argv[1:2] == ["--dispatch"]:
        dispatch(sys.argv[2:])
    else:
        body, spec = sys.argv[1], sys.argv[2]
        tests = [(l.split()[0], l.split()[1]) for l in open(spec) if l.strip()]
        sys.stdout.write(open(body).read() + tail(tests))
