; UB tests for the `alloca` instruction.
;
; LangRef (alloca, Semantics): "If the element count is undef or poison, this
; instruction has undefined behavior."  Also: "The operation itself is
; undefined if there is insufficient stack space for the allocation."
; LangRef (Allocated Objects): "the size of all allocated objects must be
; non-negative and not exceed the largest signed integer that fits into the
; index type."
;
; NOTE: the "insufficient stack space" / "size exceeds the largest signed
; index" cases (e.g. `alloca i8, i64 -1`) are not included as executable tests:
; under the infinite-pointer parameterization of the extracted interpreter they
; would try to materialize an enormous allocation rather than terminate.

define i32 @alloca_count(i32 %n) {
  %p = alloca i32, i32 %n                         ; <- UB @alloca_count
  store i32 1, ptr %p
  ret i32 0
}

; ASSERT UB 16: call i32 @alloca_count(i32 poison)
; ASSERT SUCCEEDS: call i32 @alloca_count(i32 4)

define i32 @alloca_undef_count() {
  %p = alloca i32, i32 undef                      ; <- UB @alloca_undef_count
  ret i32 0
}

; ASSERT UB 25: call i32 @alloca_undef_count()

; A zero-sized allocation is legal (the pointer may not be unique) ...
define i32 @alloca_zero_ok() {
  %p = alloca i32, i32 0
  ret i32 0
}

; ASSERT SUCCEEDS: call i32 @alloca_zero_ok()

; ... but there are no bytes to access through it.
define i32 @alloca_zero_store() {
  %p = alloca i32, i32 0
  store i32 1, ptr %p                             ; <- UB @alloca_zero_store
  ret i32 0
}

; ASSERT UB 42: call i32 @alloca_zero_store()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 21): ASSERT UB 16: call i32 @alloca_count(i32 poison)
define i32 @ub_case_0() {
  %r = call i32 @alloca_count(i32 poison)
  ret i32 %r
}

; case 1 (line 22): ASSERT SUCCEEDS: call i32 @alloca_count(i32 4)
define i32 @ub_case_1() {
  %r = call i32 @alloca_count(i32 4)
  ret i32 %r
}

; case 2 (line 29): ASSERT UB 25: call i32 @alloca_undef_count()
define i32 @ub_case_2() {
  %r = call i32 @alloca_undef_count()
  ret i32 %r
}

; case 3 (line 37): ASSERT SUCCEEDS: call i32 @alloca_zero_ok()
define i32 @ub_case_3() {
  %r = call i32 @alloca_zero_ok()
  ret i32 %r
}

; case 4 (line 46): ASSERT UB 42: call i32 @alloca_zero_store()
define i32 @ub_case_4() {
  %r = call i32 @alloca_zero_store()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
