; UB tests for the `atomicrmw` instruction.
;
; atomicrmw dereferences its pointer operand, so the load/store rules apply:
; LangRef (Poison Values): immediate UB if poison is "The pointer operand of a
; load, store or any other pointer dereferencing instruction".
; LangRef (Pointer Aliasing Rules): a null pointer is associated with no
; address.

define i32 @atomicrmw(ptr %p) {
  %old = atomicrmw add ptr %p, i32 1 seq_cst      ; <- UB @atomicrmw
  ret i32 %old
}

; ASSERT UB 10: call i32 @atomicrmw(ptr null)
; ASSERT UB 10: call i32 @atomicrmw(ptr poison)

define i32 @atomicrmw_ok() {
  %p = alloca i32
  store i32 41, ptr %p
  %old = call i32 @atomicrmw(ptr %p)
  %v = load i32, ptr %p
  ret i32 %v
}

; ASSERT EQ: i32 42 = call i32 @atomicrmw_ok()

define i32 @atomicrmw_oob() {
  %p = alloca i32
  %q = getelementptr i32, ptr %p, i64 1
  %old = atomicrmw xchg ptr %q, i32 1 seq_cst     ; <- UB @atomicrmw_oob
  ret i32 %old
}

; ASSERT UB 30: call i32 @atomicrmw_oob()

; Overestimated alignment.
define i32 @atomicrmw_misaligned() {
  %p = alloca [2 x i32], align 8
  %q = getelementptr i8, ptr %p, i64 4
  %old = atomicrmw add ptr %q, i32 1 seq_cst, align 8 ; <- UB @atomicrmw_misaligned
  ret i32 %old
}

; ASSERT UB 40: call i32 @atomicrmw_misaligned()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 14): ASSERT UB 10: call i32 @atomicrmw(ptr null)
define i32 @ub_case_0() {
  %r = call i32 @atomicrmw(ptr null)
  ret i32 %r
}

; case 1 (line 15): ASSERT UB 10: call i32 @atomicrmw(ptr poison)
define i32 @ub_case_1() {
  %r = call i32 @atomicrmw(ptr poison)
  ret i32 %r
}

; case 2 (line 25): ASSERT EQ: i32 42 = call i32 @atomicrmw_ok()
define i32 @ub_case_2() {
  %r = call i32 @atomicrmw_ok()
  ret i32 %r
}

; case 3 (line 34): ASSERT UB 30: call i32 @atomicrmw_oob()
define i32 @ub_case_3() {
  %r = call i32 @atomicrmw_oob()
  ret i32 %r
}

; case 4 (line 44): ASSERT UB 40: call i32 @atomicrmw_misaligned()
define i32 @ub_case_4() {
  %r = call i32 @atomicrmw_misaligned()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
