; UB tests for the `br` instruction.
;
; LangRef (br, Semantics): "If 'cond' is poison or undef, this instruction has
; undefined behavior."
; LangRef (Undefined Values): "Branching on an undefined value is undefined
; behavior."

define i32 @br(i1 %c) {
entry:
  br i1 %c, label %t, label %f                    ; <- UB @br
t:
  ret i32 1
f:
  ret i32 0
}

; ASSERT UB 10: call i32 @br(i1 poison)
; ASSERT EQ: i32 1 = call i32 @br(i1 1)
; ASSERT EQ: i32 0 = call i32 @br(i1 0)

define i32 @br_undef() {
entry:
  br i1 undef, label %t, label %f                 ; <- UB @br_undef
t:
  ret i32 1
f:
  ret i32 0
}

; ASSERT UB 23: call i32 @br_undef()

; Both successors equal: still UB (LangRef Poison Values example).
define i32 @br_same_target(i1 %c) {
entry:
  br i1 %c, label %end, label %end                ; <- UB @br_same_target
end:
  ret i32 0
}

; ASSERT UB 35: call i32 @br_same_target(i1 poison)

; Poison flowing through a computation (LangRef Poison Values example).
define i32 @br_on_icmp_of_poison() {
entry:
  %p = sub nuw i32 0, 1
  %cmp = icmp slt i32 %p, 0
  br i1 %cmp, label %t, label %f                  ; <- UB @br_on_icmp_of_poison
t:
  ret i32 1
f:
  ret i32 0
}

; ASSERT UB 47: call i32 @br_on_icmp_of_poison()

; Control: freeze makes the branch well-defined (nondeterministic target).
define i32 @br_freeze(i1 %c) {
entry:
  %fc = freeze i1 %c
  br i1 %fc, label %t, label %f
t:
  ret i32 1
f:
  ret i32 0
}

; ASSERT SUCCEEDS: call i32 @br_freeze(i1 poison)

; Control: `select` on poison is poison, not UB; only branching on it is UB.
define i32 @select_poison(i1 %c) {
  %r = select i1 %c, i32 1, i32 0
  ret i32 %r
}

; ASSERT EQ: i32 poison = call i32 @select_poison(i1 poison)

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 17): ASSERT UB 10: call i32 @br(i1 poison)
define i32 @ub_case_0() {
  %r = call i32 @br(i1 poison)
  ret i32 %r
}

; case 1 (line 18): ASSERT EQ: i32 1 = call i32 @br(i1 1)
define i32 @ub_case_1() {
  %r = call i32 @br(i1 1)
  ret i32 %r
}

; case 2 (line 19): ASSERT EQ: i32 0 = call i32 @br(i1 0)
define i32 @ub_case_2() {
  %r = call i32 @br(i1 0)
  ret i32 %r
}

; case 3 (line 30): ASSERT UB 23: call i32 @br_undef()
define i32 @ub_case_3() {
  %r = call i32 @br_undef()
  ret i32 %r
}

; case 4 (line 40): ASSERT UB 35: call i32 @br_same_target(i1 poison)
define i32 @ub_case_4() {
  %r = call i32 @br_same_target(i1 poison)
  ret i32 %r
}

; case 5 (line 54): ASSERT UB 47: call i32 @br_on_icmp_of_poison()
define i32 @ub_case_5() {
  %r = call i32 @br_on_icmp_of_poison()
  ret i32 %r
}

; case 6 (line 67): ASSERT SUCCEEDS: call i32 @br_freeze(i1 poison)
define i32 @ub_case_6() {
  %r = call i32 @br_freeze(i1 poison)
  ret i32 %r
}

; case 7 (line 75): ASSERT EQ: i32 poison = call i32 @select_poison(i1 poison)
define i32 @ub_case_7() {
  %r = call i32 @select_poison(i1 poison)
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
    i32 5, label %case5
    i32 6, label %case6
    i32 7, label %case7
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case5:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 5)
  %c5_r = call i32 @ub_case_5()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 5)
  %c5_0 = sext i32 %c5_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c5_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case6:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 6)
  %c6_r = call i32 @ub_case_6()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 6)
  %c6_0 = sext i32 %c6_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c6_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case7:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 7)
  %c7_r = call i32 @ub_case_7()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 7)
  %c7_0 = sext i32 %c7_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c7_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
