; UB tests for the `call` instruction itself: the callee operand and the
; calling convention.  Parameter attributes are in call-param-attrs.ll,
; return-value attributes in ret.ll, function attributes in call-fn-attrs.ll,
; and pointer-argument capability attributes in call-ptr-attrs.ll.
;
; LangRef (Poison Values): immediate UB if poison is "The callee operand of a
; call or invoke instruction".
; LangRef (Calling Conventions): "The calling convention of any pair of
; dynamic caller/callee must match, or the behavior of the program is
; undefined."  (call, Arguments): "The calling convention of the call must
; match the calling convention of the target function, or else the behavior
; is undefined."
; LangRef (call, Semantics): "if the signature of the call does not match the
; signature of the called function, the behavior is target-specific.  For a
; significant mismatch, this likely results in undefined behavior."  (Not
; tested: the LangRef does not pin this down.)

@data = global i32 0

define i32 @callee() {
  ret i32 7
}

define fastcc i32 @fast_callee() {
  ret i32 8
}

define i32 @call_ptr(ptr %f) {
  %r = call i32 %f()                              ; <- UB @call_ptr
  ret i32 %r
}

; ASSERT UB 29: call i32 @call_ptr(ptr poison)
; ASSERT UB 29: call i32 @call_ptr(ptr null)

define i32 @call_ptr_ok() {
  %r = call i32 @call_ptr(ptr @callee)
  ret i32 %r
}

; ASSERT EQ: i32 7 = call i32 @call_ptr_ok()

define i32 @call_undef() {
  %r = call i32 undef()                           ; <- UB @call_undef
  ret i32 %r
}

; ASSERT UB 44: call i32 @call_undef()

; A null *address* is enough, whatever the provenance: `inttoptr i64 0` is the
; null pointer in address space 0.
define i32 @call_inttoptr_null() {
  %f = inttoptr i64 0 to ptr
  %r = call i32 %f()                              ; <- UB @call_inttoptr_null
  ret i32 %r
}

; ASSERT UB 54: call i32 @call_inttoptr_null()

; Calling a pointer to data rather than to a function.
define i32 @call_data_pointer() {
  %r = call i32 @data()                           ; <- UB @call_data_pointer
  ret i32 %r
}

; ASSERT UB 62: call i32 @call_data_pointer()

; Calling-convention mismatch: fastcc callee called with the default (ccc).
define i32 @call_cc_mismatch() {
  %r = call i32 @fast_callee()                    ; <- UB @call_cc_mismatch
  ret i32 %r
}

; ASSERT UB 70: call i32 @call_cc_mismatch()

; ... and the other way round.
define i32 @call_cc_mismatch2() {
  %r = call fastcc i32 @callee()                  ; <- UB @call_cc_mismatch2
  ret i32 %r
}

; ASSERT UB 78: call i32 @call_cc_mismatch2()

define i32 @call_cc_ok() {
  %r = call fastcc i32 @fast_callee()
  ret i32 %r
}

; ASSERT EQ: i32 8 = call i32 @call_cc_ok()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 33): ASSERT UB 29: call i32 @call_ptr(ptr poison)
define i32 @ub_case_0() {
  %r = call i32 @call_ptr(ptr poison)
  ret i32 %r
}

; case 1 (line 34): ASSERT UB 29: call i32 @call_ptr(ptr null)
define i32 @ub_case_1() {
  %r = call i32 @call_ptr(ptr null)
  ret i32 %r
}

; case 2 (line 41): ASSERT EQ: i32 7 = call i32 @call_ptr_ok()
define i32 @ub_case_2() {
  %r = call i32 @call_ptr_ok()
  ret i32 %r
}

; case 3 (line 48): ASSERT UB 44: call i32 @call_undef()
define i32 @ub_case_3() {
  %r = call i32 @call_undef()
  ret i32 %r
}

; case 4 (line 58): ASSERT UB 54: call i32 @call_inttoptr_null()
define i32 @ub_case_4() {
  %r = call i32 @call_inttoptr_null()
  ret i32 %r
}

; case 5 (line 66): ASSERT UB 62: call i32 @call_data_pointer()
define i32 @ub_case_5() {
  %r = call i32 @call_data_pointer()
  ret i32 %r
}

; case 6 (line 74): ASSERT UB 70: call i32 @call_cc_mismatch()
define i32 @ub_case_6() {
  %r = call i32 @call_cc_mismatch()
  ret i32 %r
}

; case 7 (line 82): ASSERT UB 78: call i32 @call_cc_mismatch2()
define i32 @ub_case_7() {
  %r = call i32 @call_cc_mismatch2()
  ret i32 %r
}

; case 8 (line 89): ASSERT EQ: i32 8 = call i32 @call_cc_ok()
define i32 @ub_case_8() {
  %r = call i32 @call_cc_ok()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
    i32 5, label %case5
    i32 6, label %case6
    i32 7, label %case7
    i32 8, label %case8
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case5:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 5)
  %c5_r = call i32 @ub_case_5()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 5)
  %c5_0 = sext i32 %c5_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c5_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case6:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 6)
  %c6_r = call i32 @ub_case_6()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 6)
  %c6_0 = sext i32 %c6_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c6_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case7:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 7)
  %c7_r = call i32 @ub_case_7()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 7)
  %c7_0 = sext i32 %c7_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c7_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case8:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 8)
  %c8_r = call i32 @ub_case_8()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 8)
  %c8_0 = sext i32 %c8_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c8_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
