; UB tests for function attributes that involve unwinding.
;
; LangRef (nounwind): "If the function does raise an exception, its runtime
; behavior is undefined."
; LangRef (noreturn): "Annotated functions may still raise an exception".
;
; Exceptions are raised with Vellvm's `@llvm.vellvm.internal.throw()` (see
; tests/exceptions/README.md), so this file runs only under Vellvm; it cannot
; be compiled natively.

declare void @llvm.vellvm.internal.throw()

define i64 @personality(i32 %v, i32 %a, i64 %c, i8* %e, i8* %x) {
  ret i64 0
}

; Control: a noreturn function that does not return (here: it throws) is fine.
define void @noreturn_throws() noreturn {
  call void @llvm.vellvm.internal.throw()
  unreachable
}

define i32 @call_noreturn_throws() personality i64 (i32, i32, i64, i8*, i8*)* @personality {
entry:
  invoke void @noreturn_throws() to label %ok unwind label %caught
ok:
  ret i32 0
caught:
  %lp = landingpad { ptr, i64 } catch ptr null
  ret i32 1
}

; ASSERT EQ: i32 1 = call i32 @call_noreturn_throws()

; ------------------------------------------------------------ nounwind

define void @nounwind_throws() nounwind {
  call void @llvm.vellvm.internal.throw()         ; <- UB @call_nounwind_throws
  unreachable
}

define i32 @call_nounwind_throws() personality i64 (i32, i32, i64, i8*, i8*)* @personality {
entry:
  invoke void @nounwind_throws() to label %ok unwind label %caught
ok:
  ret i32 0
caught:
  %lp = landingpad { ptr, i64 } catch ptr null
  ret i32 1
}

; ASSERT UB 38: call i32 @call_nounwind_throws()

; nounwind on the call site.
define void @throws() {
  call void @llvm.vellvm.internal.throw()
  unreachable
}

define i32 @call_nounwind_callsite() personality i64 (i32, i32, i64, i8*, i8*)* @personality {
entry:
  invoke void @throws() nounwind to label %ok unwind label %caught ; <- UB @call_nounwind_callsite
ok:
  ret i32 0
caught:
  %lp = landingpad { ptr, i64 } catch ptr null
  ret i32 1
}

; ASSERT UB 62: call i32 @call_nounwind_callsite()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 33): ASSERT EQ: i32 1 = call i32 @call_noreturn_throws()
define i32 @ub_case_0() {
  %r = call i32 @call_noreturn_throws()
  ret i32 %r
}

; case 1 (line 52): ASSERT UB 38: call i32 @call_nounwind_throws()
define i32 @ub_case_1() {
  %r = call i32 @call_nounwind_throws()
  ret i32 %r
}

; case 2 (line 70): ASSERT UB 62: call i32 @call_nounwind_callsite()
define i32 @ub_case_2() {
  %r = call i32 @call_nounwind_callsite()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
