; UB tests for the `nofpclass` parameter attribute on `call`.
;
; LangRef (nofpclass(<test mask>)): "If the value is a floating-point class
; indicated by the nofpclass test mask, a poison value is passed or returned
; instead."  Combined with `noundef` (LangRef noundef: "If the value
; representation contains any undefined or poison bits, the behavior is
; undefined") the violation is immediate UB.
;
; NOTE: Vellvm's parser does not currently accept `nofpclass`, so this whole
; file fails to parse.

define i32 @take_nonan_noundef(double noundef nofpclass(nan) %x) {
  ret i32 0
}

define i32 @nofpclass_noundef_nan() {
  %nan = fdiv double 0.0, 0.0
  %r = call i32 @take_nonan_noundef(double %nan)  ; <- UB @nofpclass_noundef_nan
  ret i32 %r
}

; ASSERT UB 18: call i32 @nofpclass_noundef_nan()

define i32 @take_nozero_noundef(double noundef nofpclass(zero) %x) {
  ret i32 0
}

define i32 @nofpclass_noundef_negzero() {
  %r = call i32 @take_nozero_noundef(double -0.0) ; <- UB @nofpclass_noundef_negzero
  ret i32 %r
}

; ASSERT UB 29: call i32 @nofpclass_noundef_negzero()

define i32 @nofpclass_noundef_ok() {
  %r = call i32 @take_nonan_noundef(double 1.0)
  ret i32 %r
}

; ASSERT EQ: i32 0 = call i32 @nofpclass_noundef_ok()

; nofpclass without noundef: poison.
define double @nonan_observe(double nofpclass(nan) %x) {
  ret double %x
}

define double @nofpclass_only_nan() {
  %nan = fdiv double 0.0, 0.0
  %r = call double @nonan_observe(double %nan)
  ret double %r
}

; ASSERT EQ: double poison = call double @nofpclass_only_nan()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 22): ASSERT UB 18: call i32 @nofpclass_noundef_nan()
define i32 @ub_case_0() {
  %r = call i32 @nofpclass_noundef_nan()
  ret i32 %r
}

; case 1 (line 33): ASSERT UB 29: call i32 @nofpclass_noundef_negzero()
define i32 @ub_case_1() {
  %r = call i32 @nofpclass_noundef_negzero()
  ret i32 %r
}

; case 2 (line 40): ASSERT EQ: i32 0 = call i32 @nofpclass_noundef_ok()
define i32 @ub_case_2() {
  %r = call i32 @nofpclass_noundef_ok()
  ret i32 %r
}

; case 3 (line 53): ASSERT EQ: double poison = call double @nofpclass_only_nan()
define double @ub_case_3() {
  %r = call double @nofpclass_only_nan()
  ret double %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call double @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_fp, double %c3_r)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
