; UB tests for the `nofreeobj` attribute.
;
; LangRef (nofreeobj): "On arguments, this indicates that the underlying object
; of the argument cannot be freed during the execution of the function. ...
; Unlike nofree, it is not possible to free the underlying object through a
; different pointer either."  "On return values, ... any free of the
; underlying object must happen-before the function returns, otherwise the
; behavior is undefined."
;
; NOTE: neither Vellvm's parser nor LLVM 23.1 accepts `nofreeobj` yet (it is
; newer than that release), so this file only runs once support lands.

declare ptr @malloc(i64)
declare void @free(ptr)

define void @nofreeobj_frees_other(ptr nofreeobj %p, ptr %q) {
  call void @free(ptr %q)                         ; <- UB @call_nofreeobj_frees_other
  ret void
}

define i32 @call_nofreeobj_frees_other() {
  %p = call ptr @malloc(i64 4)
  call void @nofreeobj_frees_other(ptr %p, ptr %p)
  ret i32 0
}

; ASSERT UB 17: call i32 @call_nofreeobj_frees_other()

define nofreeobj ptr @ret_nofreeobj() {
  %p = call ptr @malloc(i64 4)
  ret ptr %p
}

define i32 @free_nofreeobj_return() {
  %p = call ptr @ret_nofreeobj()
  call void @free(ptr %p)                         ; <- UB @free_nofreeobj_return
  ret i32 0
}

; ASSERT UB 36: call i32 @free_nofreeobj_return()


; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 27): ASSERT UB 17: call i32 @call_nofreeobj_frees_other()
define i32 @ub_case_0() {
  %r = call i32 @call_nofreeobj_frees_other()
  ret i32 %r
}

; case 1 (line 40): ASSERT UB 36: call i32 @free_nofreeobj_return()
define i32 @ub_case_1() {
  %r = call i32 @free_nofreeobj_return()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
