; UB tests for pointer-attribute features that Vellvm's parser does not
; accept yet.  This whole file currently fails to parse; each section is
; self-contained so it can be moved into call-ptr-attrs.ll once supported.
;
; LangRef (captures(...)): "it is possible to specify that some components are
; only captured in certain locations. Currently only the return value (ret)
; and other (default) locations are supported."
; LangRef (!captures metadata on store): "store ptr %x, ptr %y, !captures
; !{!"address"} indicates that the copy of pointer %x stored to location %y
; will only be used to inspect its integral address value, and not
; dereferenced. Dereferencing the pointer would result in undefined behavior."
; (`nofreeobj` is in call-ptr-attrs-nofreeobj.ll.)

@slot = global ptr null

; ------------------------------------------------------- captures(ret: ...)

define ptr @return_arg_ret(ptr captures(ret: address, provenance) %p) {
  ret ptr %p
}

define i32 @captures_ret_ok() {
  %a = alloca i32
  %p = call ptr @return_arg_ret(ptr %a)
  store i32 2, ptr %p
  %v = load i32, ptr %a
  ret i32 %v
}

; ASSERT EQ: i32 2 = call i32 @captures_ret_ok()

; Captured through the return value only: stashing it elsewhere and using
; that copy after return is UB.
define ptr @stash_and_return(ptr captures(ret: address, provenance) %p) {
  store ptr %p, ptr @slot
  ret ptr %p
}

define i32 @captures_ret_other_path() {
  %a = alloca i32
  %r = call ptr @stash_and_return(ptr %a)
  %p = load ptr, ptr @slot
  store i32 1, ptr %p                             ; <- UB @captures_ret_other_path
  ret i32 0
}

; ASSERT UB 43: call i32 @captures_ret_other_path()

; ------------------------------------------------------- !captures metadata

define i32 @md_captures_address() {
  %a = alloca i32
  store ptr %a, ptr @slot, !captures !0
  %p = load ptr, ptr @slot
  store i32 1, ptr %p                             ; <- UB @md_captures_address
  ret i32 0
}

; ASSERT UB 55: call i32 @md_captures_address()

define i32 @md_captures_read_provenance() {
  %a = alloca i32
  store i32 4, ptr %a
  store ptr %a, ptr @slot, !captures !1
  %p = load ptr, ptr @slot
  %v = load i32, ptr %p
  store i32 1, ptr %p                             ; <- UB @md_captures_read_provenance
  ret i32 %v
}

; ASSERT UB 67: call i32 @md_captures_read_provenance()

!0 = !{!"address"}
!1 = !{!"address", !"read_provenance"}

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 30): ASSERT EQ: i32 2 = call i32 @captures_ret_ok()
define i32 @ub_case_0() {
  %r = call i32 @captures_ret_ok()
  ret i32 %r
}

; case 1 (line 47): ASSERT UB 43: call i32 @captures_ret_other_path()
define i32 @ub_case_1() {
  %r = call i32 @captures_ret_other_path()
  ret i32 %r
}

; case 2 (line 59): ASSERT UB 55: call i32 @md_captures_address()
define i32 @ub_case_2() {
  %r = call i32 @md_captures_address()
  ret i32 %r
}

; case 3 (line 71): ASSERT UB 67: call i32 @md_captures_read_provenance()
define i32 @ub_case_3() {
  %r = call i32 @md_captures_read_provenance()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
