; UB tests for the `cmpxchg` instruction.
;
; cmpxchg dereferences its pointer operand, so the load/store rules apply
; (LangRef Poison Values; Pointer Aliasing Rules).
; LangRef (cmpxchg, Arguments): "The pointer passed into cmpxchg must have
; alignment greater than or equal to the size in memory of the operand."
;
; NOTE: Vellvm additionally raises UB when the *comparison* involves poison
; ("comparing poison in atomiccmpxchg").  LangRef does not list that case, so
; it is not asserted here either way.

define i32 @cmpxchg(ptr %p) {
  %r = cmpxchg ptr %p, i32 0, i32 1 seq_cst seq_cst ; <- UB @cmpxchg
  %v = extractvalue { i32, i1 } %r, 0
  ret i32 %v
}

; ASSERT UB 13: call i32 @cmpxchg(ptr null)
; ASSERT UB 13: call i32 @cmpxchg(ptr poison)

define i32 @cmpxchg_ok() {
  %p = alloca i32
  store i32 0, ptr %p
  %r = call i32 @cmpxchg(ptr %p)
  %v = load i32, ptr %p
  ret i32 %v
}

; ASSERT EQ: i32 1 = call i32 @cmpxchg_ok()

define i32 @cmpxchg_misaligned() {
  %p = alloca [2 x i32], align 8
  store [2 x i32] [i32 0, i32 0], ptr %p
  %q = getelementptr i8, ptr %p, i64 2
  %r = cmpxchg ptr %q, i32 0, i32 1 seq_cst seq_cst, align 2 ; <- UB @cmpxchg_misaligned
  ret i32 0
}

; ASSERT UB 35: call i32 @cmpxchg_misaligned()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 18): ASSERT UB 13: call i32 @cmpxchg(ptr null)
define i32 @ub_case_0() {
  %r = call i32 @cmpxchg(ptr null)
  ret i32 %r
}

; case 1 (line 19): ASSERT UB 13: call i32 @cmpxchg(ptr poison)
define i32 @ub_case_1() {
  %r = call i32 @cmpxchg(ptr poison)
  ret i32 %r
}

; case 2 (line 29): ASSERT EQ: i32 1 = call i32 @cmpxchg_ok()
define i32 @ub_case_2() {
  %r = call i32 @cmpxchg_ok()
  ret i32 %r
}

; case 3 (line 39): ASSERT UB 35: call i32 @cmpxchg_misaligned()
define i32 @ub_case_3() {
  %r = call i32 @cmpxchg_misaligned()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
