; UB tests for the `indirectbr` instruction.
;
; LangRef (indirectbr, Semantics): "All possible destination blocks must be
; listed in the label list, otherwise this instruction has undefined behavior.
; This implies that jumps to labels defined in other functions have undefined
; behavior as well.  If 'address' is poison or undef, this instruction has
; undefined behavior."
;
; NOTE: Vellvm's parser does not accept `blockaddress` constants, so the
; "destination not in the label list" and "label in another function" cases
; cannot be written yet.  They would look like:
;
;   indirectbr ptr blockaddress(@f, %c), [ label %a, label %b ]   ; UB
;   indirectbr ptr blockaddress(@g, %x), [ label %a ]             ; UB

define i32 @indirectbr_poison() {
entry:
  indirectbr ptr poison, [ label %a, label %b ]   ; <- UB @indirectbr_poison
a:
  ret i32 1
b:
  ret i32 2
}

; ASSERT UB 18: call i32 @indirectbr_poison()

define i32 @indirectbr_undef() {
entry:
  indirectbr ptr undef, [ label %a, label %b ]    ; <- UB @indirectbr_undef
a:
  ret i32 1
b:
  ret i32 2
}

; ASSERT UB 29: call i32 @indirectbr_undef()

; A null address is not the address of any listed block.
define i32 @indirectbr_null() {
entry:
  indirectbr ptr null, [ label %a, label %b ]     ; <- UB @indirectbr_null
a:
  ret i32 1
b:
  ret i32 2
}

; ASSERT UB 41: call i32 @indirectbr_null()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 25): ASSERT UB 18: call i32 @indirectbr_poison()
define i32 @ub_case_0() {
  %r = call i32 @indirectbr_poison()
  ret i32 %r
}

; case 1 (line 36): ASSERT UB 29: call i32 @indirectbr_undef()
define i32 @ub_case_1() {
  %r = call i32 @indirectbr_undef()
  ret i32 %r
}

; case 2 (line 48): ASSERT UB 41: call i32 @indirectbr_null()
define i32 @ub_case_2() {
  %r = call i32 @indirectbr_null()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
