; UB tests for the `sdiv` instruction.
;
; LangRef (sdiv, Semantics): "Division by zero is undefined behavior. For
; vectors, if any element of the divisor is zero, the operation has undefined
; behavior. Overflow also leads to undefined behavior; this is a rare case, but
; can occur, for example, by doing a 32-bit division of -2147483648 by -1."
; LangRef (Poison Values): poison as the divisor of sdiv is immediate UB.

define i32 @sdiv(i32 %a, i32 %b) {
  %r = sdiv i32 %a, %b                            ; <- UB @sdiv
  ret i32 %r
}

; ASSERT UB 10: call i32 @sdiv(i32 7, i32 0)
; ASSERT UB 10: call i32 @sdiv(i32 7, i32 poison)
; ASSERT UB 10: call i32 @sdiv(i32 -2147483648, i32 -1)
; ASSERT EQ: i32 -3 = call i32 @sdiv(i32 -7, i32 2)
; ASSERT EQ: i32 2147483647 = call i32 @sdiv(i32 -2147483647, i32 -1)
; ASSERT EQ: i32 poison = call i32 @sdiv(i32 poison, i32 2)

; Overflow at a non-standard width.
define i8 @sdiv_i8(i8 %a, i8 %b) {
  %r = sdiv i8 %a, %b                             ; <- UB @sdiv_i8
  ret i8 %r
}

; ASSERT UB 23: call i8 @sdiv_i8(i8 -128, i8 -1)
; ASSERT EQ: i8 -64 = call i8 @sdiv_i8(i8 -128, i8 2)

; A poison dividend with a -1 divisor is UB: LangRef (Poison Values) says
; immediate UB occurs if poison is used as "an instruction operand that has any
; values that trigger undefined behavior", and the dividend INT_MIN does.
; With any other divisor a poison dividend only yields poison.
; ASSERT UB 23: call i8 @sdiv_i8(i8 poison, i8 -1)
; ASSERT EQ: i8 poison = call i8 @sdiv_i8(i8 poison, i8 2)

define i32 @sdiv_undef_divisor() {
  %r = sdiv i32 7, undef                          ; <- UB @sdiv_undef_divisor
  ret i32 %r
}

; ASSERT UB 38: call i32 @sdiv_undef_divisor()

define <2 x i32> @sdiv_vec_zero_lane() {
  %r = sdiv <2 x i32> <i32 8, i32 8>, <i32 2, i32 0> ; <- UB @sdiv_vec_zero_lane
  ret <2 x i32> %r
}

; ASSERT UB 45: call <2 x i32> @sdiv_vec_zero_lane()

define <2 x i32> @sdiv_vec_overflow_lane() {
  %r = sdiv <2 x i32> <i32 8, i32 -2147483648>, <i32 2, i32 -1> ; <- UB @sdiv_vec_overflow_lane
  ret <2 x i32> %r
}

; ASSERT UB 52: call <2 x i32> @sdiv_vec_overflow_lane()

define <2 x i32> @sdiv_vec_poison_lane() {
  %r = sdiv <2 x i32> <i32 8, i32 8>, <i32 2, i32 poison> ; <- UB @sdiv_vec_poison_lane
  ret <2 x i32> %r
}

; ASSERT UB 59: call <2 x i32> @sdiv_vec_poison_lane()

; `exact` violations produce poison, not UB.
define i32 @sdiv_exact(i32 %a, i32 %b) {
  %r = sdiv exact i32 %a, %b
  ret i32 %r
}

; ASSERT EQ: i32 poison = call i32 @sdiv_exact(i32 7, i32 2)

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 14): ASSERT UB 10: call i32 @sdiv(i32 7, i32 0)
define i32 @ub_case_0() {
  %r = call i32 @sdiv(i32 7, i32 0)
  ret i32 %r
}

; case 1 (line 15): ASSERT UB 10: call i32 @sdiv(i32 7, i32 poison)
define i32 @ub_case_1() {
  %r = call i32 @sdiv(i32 7, i32 poison)
  ret i32 %r
}

; case 2 (line 16): ASSERT UB 10: call i32 @sdiv(i32 -2147483648, i32 -1)
define i32 @ub_case_2() {
  %r = call i32 @sdiv(i32 -2147483648, i32 -1)
  ret i32 %r
}

; case 3 (line 17): ASSERT EQ: i32 -3 = call i32 @sdiv(i32 -7, i32 2)
define i32 @ub_case_3() {
  %r = call i32 @sdiv(i32 -7, i32 2)
  ret i32 %r
}

; case 4 (line 18): ASSERT EQ: i32 2147483647 = call i32 @sdiv(i32 -2147483647, i32 -1)
define i32 @ub_case_4() {
  %r = call i32 @sdiv(i32 -2147483647, i32 -1)
  ret i32 %r
}

; case 5 (line 19): ASSERT EQ: i32 poison = call i32 @sdiv(i32 poison, i32 2)
define i32 @ub_case_5() {
  %r = call i32 @sdiv(i32 poison, i32 2)
  ret i32 %r
}

; case 6 (line 27): ASSERT UB 23: call i8 @sdiv_i8(i8 -128, i8 -1)
define i8 @ub_case_6() {
  %r = call i8 @sdiv_i8(i8 -128, i8 -1)
  ret i8 %r
}

; case 7 (line 28): ASSERT EQ: i8 -64 = call i8 @sdiv_i8(i8 -128, i8 2)
define i8 @ub_case_7() {
  %r = call i8 @sdiv_i8(i8 -128, i8 2)
  ret i8 %r
}

; case 8 (line 34): ASSERT UB 23: call i8 @sdiv_i8(i8 poison, i8 -1)
define i8 @ub_case_8() {
  %r = call i8 @sdiv_i8(i8 poison, i8 -1)
  ret i8 %r
}

; case 9 (line 35): ASSERT EQ: i8 poison = call i8 @sdiv_i8(i8 poison, i8 2)
define i8 @ub_case_9() {
  %r = call i8 @sdiv_i8(i8 poison, i8 2)
  ret i8 %r
}

; case 10 (line 42): ASSERT UB 38: call i32 @sdiv_undef_divisor()
define i32 @ub_case_10() {
  %r = call i32 @sdiv_undef_divisor()
  ret i32 %r
}

; case 11 (line 49): ASSERT UB 45: call <2 x i32> @sdiv_vec_zero_lane()
define <2 x i32> @ub_case_11() {
  %r = call <2 x i32> @sdiv_vec_zero_lane()
  ret <2 x i32> %r
}

; case 12 (line 56): ASSERT UB 52: call <2 x i32> @sdiv_vec_overflow_lane()
define <2 x i32> @ub_case_12() {
  %r = call <2 x i32> @sdiv_vec_overflow_lane()
  ret <2 x i32> %r
}

; case 13 (line 63): ASSERT UB 59: call <2 x i32> @sdiv_vec_poison_lane()
define <2 x i32> @ub_case_13() {
  %r = call <2 x i32> @sdiv_vec_poison_lane()
  ret <2 x i32> %r
}

; case 14 (line 71): ASSERT EQ: i32 poison = call i32 @sdiv_exact(i32 7, i32 2)
define i32 @ub_case_14() {
  %r = call i32 @sdiv_exact(i32 7, i32 2)
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
    i32 5, label %case5
    i32 6, label %case6
    i32 7, label %case7
    i32 8, label %case8
    i32 9, label %case9
    i32 10, label %case10
    i32 11, label %case11
    i32 12, label %case12
    i32 13, label %case13
    i32 14, label %case14
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case5:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 5)
  %c5_r = call i32 @ub_case_5()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 5)
  %c5_0 = sext i32 %c5_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c5_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case6:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 6)
  %c6_r = call i8 @ub_case_6()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 6)
  %c6_0 = sext i8 %c6_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c6_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case7:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 7)
  %c7_r = call i8 @ub_case_7()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 7)
  %c7_0 = sext i8 %c7_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c7_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case8:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 8)
  %c8_r = call i8 @ub_case_8()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 8)
  %c8_0 = sext i8 %c8_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c8_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case9:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 9)
  %c9_r = call i8 @ub_case_9()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 9)
  %c9_0 = sext i8 %c9_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c9_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case10:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 10)
  %c10_r = call i32 @ub_case_10()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 10)
  %c10_0 = sext i32 %c10_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c10_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case11:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 11)
  %c11_r = call <2 x i32> @ub_case_11()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 11)
  %c11_0 = extractelement <2 x i32> %c11_r, i32 0
  %c11_1 = sext i32 %c11_0 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c11_1)
  %c11_2 = extractelement <2 x i32> %c11_r, i32 1
  %c11_3 = sext i32 %c11_2 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c11_3)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case12:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 12)
  %c12_r = call <2 x i32> @ub_case_12()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 12)
  %c12_0 = extractelement <2 x i32> %c12_r, i32 0
  %c12_1 = sext i32 %c12_0 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c12_1)
  %c12_2 = extractelement <2 x i32> %c12_r, i32 1
  %c12_3 = sext i32 %c12_2 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c12_3)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case13:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 13)
  %c13_r = call <2 x i32> @ub_case_13()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 13)
  %c13_0 = extractelement <2 x i32> %c13_r, i32 0
  %c13_1 = sext i32 %c13_0 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c13_1)
  %c13_2 = extractelement <2 x i32> %c13_r, i32 1
  %c13_3 = sext i32 %c13_2 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c13_3)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case14:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 14)
  %c14_r = call i32 @ub_case_14()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 14)
  %c14_0 = sext i32 %c14_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c14_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
