; UB tests for the `switch` instruction.
;
; LangRef (switch, Semantics): "If 'value' is poison or undef, this instruction
; has undefined behavior."
; LangRef (Undefined Values) examples: `switch %X, label %ret [ .. ] ; UB` for
; X = undef.

define i32 @switch(i32 %x) {
entry:
  switch i32 %x, label %d [ i32 0, label %a       ; <- UB @switch
                            i32 1, label %b ]
a:
  ret i32 10
b:
  ret i32 11
d:
  ret i32 12
}

; ASSERT UB 10: call i32 @switch(i32 poison)
; ASSERT EQ: i32 11 = call i32 @switch(i32 1)
; ASSERT EQ: i32 12 = call i32 @switch(i32 5)

define i32 @switch_undef() {
entry:
  switch i32 undef, label %d [ i32 0, label %a ]  ; <- UB @switch_undef
a:
  ret i32 10
d:
  ret i32 12
}

; ASSERT UB 26: call i32 @switch_undef()

; Empty table: the only possible destination is the default, still UB.
define i32 @switch_no_cases(i8 %x) {
entry:
  switch i8 %x, label %d [ ]                      ; <- UB @switch_no_cases
d:
  ret i32 12
}

; ASSERT UB 38: call i32 @switch_no_cases(i8 poison)
; ASSERT EQ: i32 12 = call i32 @switch_no_cases(i8 3)

; `or i8 undef, 255` separates undef from poison.  Under today's LangRef
; (Undefined Values) undef is "any value", so the `or` is always 255 and the
; switch is well defined; llubi and clang agree.  This branch follows LLVM's
; plan to replace undef by poison and denotes undef as poison, so the `or` is
; poison and switching on it is UB.
define i32 @switch_or_undef_255() {
entry:
  %x = or i8 undef, 255
  switch i8 %x, label %d [ i8 -1, label %a ]      ; <- UB @switch_or_undef_255
a:
  ret i32 10
d:
  ret i32 12
}

; ASSERT UB 54: call i32 @switch_or_undef_255()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 20): ASSERT UB 10: call i32 @switch(i32 poison)
define i32 @ub_case_0() {
  %r = call i32 @switch(i32 poison)
  ret i32 %r
}

; case 1 (line 21): ASSERT EQ: i32 11 = call i32 @switch(i32 1)
define i32 @ub_case_1() {
  %r = call i32 @switch(i32 1)
  ret i32 %r
}

; case 2 (line 22): ASSERT EQ: i32 12 = call i32 @switch(i32 5)
define i32 @ub_case_2() {
  %r = call i32 @switch(i32 5)
  ret i32 %r
}

; case 3 (line 33): ASSERT UB 26: call i32 @switch_undef()
define i32 @ub_case_3() {
  %r = call i32 @switch_undef()
  ret i32 %r
}

; case 4 (line 43): ASSERT UB 38: call i32 @switch_no_cases(i8 poison)
define i32 @ub_case_4() {
  %r = call i32 @switch_no_cases(i8 poison)
  ret i32 %r
}

; case 5 (line 44): ASSERT EQ: i32 12 = call i32 @switch_no_cases(i8 3)
define i32 @ub_case_5() {
  %r = call i32 @switch_no_cases(i8 3)
  ret i32 %r
}

; case 6 (line 61): ASSERT UB 54: call i32 @switch_or_undef_255()
define i32 @ub_case_6() {
  %r = call i32 @switch_or_undef_255()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
    i32 5, label %case5
    i32 6, label %case6
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case5:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 5)
  %c5_r = call i32 @ub_case_5()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 5)
  %c5_0 = sext i32 %c5_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c5_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case6:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 6)
  %c6_r = call i32 @ub_case_6()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 6)
  %c6_0 = sext i32 %c6_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c6_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
