; UB tests for the `udiv` instruction.
;
; LangRef (udiv, Semantics): "Division by zero is undefined behavior. For
; vectors, if any element of the divisor is zero, the operation has undefined
; behavior."
; LangRef (Poison Values): immediate UB occurs if poison is used as "the divisor
; operand of a udiv, sdiv, urem or srem instruction".
; UndefinedBehavior.md: "`udiv %x, undef` is UB since we replace undef with 0".

define i32 @udiv(i32 %a, i32 %b) {
  %r = udiv i32 %a, %b                            ; <- UB @udiv
  ret i32 %r
}

; ASSERT UB 11: call i32 @udiv(i32 7, i32 0)
; ASSERT UB 11: call i32 @udiv(i32 7, i32 poison)
; Controls: a nonzero divisor is fine, and a poison *dividend* is only poison.
; ASSERT EQ: i32 3 = call i32 @udiv(i32 7, i32 2)
; ASSERT EQ: i32 poison = call i32 @udiv(i32 poison, i32 2)

define i32 @udiv_undef_divisor() {
  %r = udiv i32 7, undef                          ; <- UB @udiv_undef_divisor
  ret i32 %r
}

; ASSERT UB 22: call i32 @udiv_undef_divisor()

; A divisor that is zero only after freeze is a concrete zero: still UB.
define i32 @udiv_freeze_zero() {
  %z = freeze i32 0
  %r = udiv i32 7, %z                             ; <- UB @udiv_freeze_zero
  ret i32 %r
}

; ASSERT UB 31: call i32 @udiv_freeze_zero()

; Vector: one zero lane makes the whole operation UB.
define <2 x i32> @udiv_vec_zero_lane() {
  %r = udiv <2 x i32> <i32 8, i32 8>, <i32 2, i32 0> ; <- UB @udiv_vec_zero_lane
  ret <2 x i32> %r
}

; ASSERT UB 39: call <2 x i32> @udiv_vec_zero_lane()

; Vector: one poison lane in the divisor is UB.
define <2 x i32> @udiv_vec_poison_lane() {
  %r = udiv <2 x i32> <i32 8, i32 8>, <i32 2, i32 poison> ; <- UB @udiv_vec_poison_lane
  ret <2 x i32> %r
}

; ASSERT UB 47: call <2 x i32> @udiv_vec_poison_lane()

; `exact` violations produce poison, not UB.
define i32 @udiv_exact(i32 %a, i32 %b) {
  %r = udiv exact i32 %a, %b
  ret i32 %r
}

; ASSERT EQ: i32 poison = call i32 @udiv_exact(i32 7, i32 2)

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 15): ASSERT UB 11: call i32 @udiv(i32 7, i32 0)
define i32 @ub_case_0() {
  %r = call i32 @udiv(i32 7, i32 0)
  ret i32 %r
}

; case 1 (line 16): ASSERT UB 11: call i32 @udiv(i32 7, i32 poison)
define i32 @ub_case_1() {
  %r = call i32 @udiv(i32 7, i32 poison)
  ret i32 %r
}

; case 2 (line 18): ASSERT EQ: i32 3 = call i32 @udiv(i32 7, i32 2)
define i32 @ub_case_2() {
  %r = call i32 @udiv(i32 7, i32 2)
  ret i32 %r
}

; case 3 (line 19): ASSERT EQ: i32 poison = call i32 @udiv(i32 poison, i32 2)
define i32 @ub_case_3() {
  %r = call i32 @udiv(i32 poison, i32 2)
  ret i32 %r
}

; case 4 (line 26): ASSERT UB 22: call i32 @udiv_undef_divisor()
define i32 @ub_case_4() {
  %r = call i32 @udiv_undef_divisor()
  ret i32 %r
}

; case 5 (line 35): ASSERT UB 31: call i32 @udiv_freeze_zero()
define i32 @ub_case_5() {
  %r = call i32 @udiv_freeze_zero()
  ret i32 %r
}

; case 6 (line 43): ASSERT UB 39: call <2 x i32> @udiv_vec_zero_lane()
define <2 x i32> @ub_case_6() {
  %r = call <2 x i32> @udiv_vec_zero_lane()
  ret <2 x i32> %r
}

; case 7 (line 51): ASSERT UB 47: call <2 x i32> @udiv_vec_poison_lane()
define <2 x i32> @ub_case_7() {
  %r = call <2 x i32> @udiv_vec_poison_lane()
  ret <2 x i32> %r
}

; case 8 (line 59): ASSERT EQ: i32 poison = call i32 @udiv_exact(i32 7, i32 2)
define i32 @ub_case_8() {
  %r = call i32 @udiv_exact(i32 7, i32 2)
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
    i32 5, label %case5
    i32 6, label %case6
    i32 7, label %case7
    i32 8, label %case8
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case5:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 5)
  %c5_r = call i32 @ub_case_5()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 5)
  %c5_0 = sext i32 %c5_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c5_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case6:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 6)
  %c6_r = call <2 x i32> @ub_case_6()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 6)
  %c6_0 = extractelement <2 x i32> %c6_r, i32 0
  %c6_1 = sext i32 %c6_0 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c6_1)
  %c6_2 = extractelement <2 x i32> %c6_r, i32 1
  %c6_3 = sext i32 %c6_2 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c6_3)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case7:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 7)
  %c7_r = call <2 x i32> @ub_case_7()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 7)
  %c7_0 = extractelement <2 x i32> %c7_r, i32 0
  %c7_1 = sext i32 %c7_0 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c7_1)
  %c7_2 = extractelement <2 x i32> %c7_r, i32 1
  %c7_3 = sext i32 %c7_2 to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c7_3)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case8:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 8)
  %c8_r = call i32 @ub_case_8()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 8)
  %c8_0 = sext i32 %c8_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c8_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
