; UB tests for the `unreachable` instruction.
;
; LangRef (unreachable): "The 'unreachable' instruction has no defined
; semantics."  Reaching it at run time is undefined behavior.

define i32 @unreachable(i1 %c) {
entry:
  br i1 %c, label %bad, label %ok
bad:
  unreachable                                     ; <- UB @unreachable
ok:
  ret i32 0
}

; ASSERT UB 10: call i32 @unreachable(i1 1)
; ASSERT EQ: i32 0 = call i32 @unreachable(i1 0)

; Reached after a call to a function that (wrongly) returns.
define void @returns() {
  ret void
}

define i32 @unreachable_after_call() {
  call void @returns()
  unreachable                                     ; <- UB @unreachable_after_call
}

; ASSERT UB 25: call i32 @unreachable_after_call()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 15): ASSERT UB 10: call i32 @unreachable(i1 1)
define i32 @ub_case_0() {
  %r = call i32 @unreachable(i1 1)
  ret i32 %r
}

; case 1 (line 16): ASSERT EQ: i32 0 = call i32 @unreachable(i1 0)
define i32 @ub_case_1() {
  %r = call i32 @unreachable(i1 0)
  ret i32 %r
}

; case 2 (line 28): ASSERT UB 25: call i32 @unreachable_after_call()
define i32 @ub_case_2() {
  %r = call i32 @unreachable_after_call()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
