; UB tests for the C library `free` function.
;
; LangRef (call): "undefined behavior in C standard library functions
; recognized by LLVM is also undefined behavior at the IR level."  C11
; 7.22.3.3: "if the argument does not match a pointer earlier returned by a
; memory management function, or if the space has been deallocated by a call to
; free or realloc, the behavior is undefined."  `free(NULL)` is a no-op.

declare ptr @malloc(i64)
declare void @free(ptr)

@g = global i32 0

define i32 @double_free() {
  %p = call ptr @malloc(i64 4)
  call void @free(ptr %p)
  call void @free(ptr %p)                         ; <- UB @double_free
  ret i32 0
}

; ASSERT UB 17: call i32 @double_free()

define i32 @free_stack() {
  %a = alloca i32
  call void @free(ptr %a)                         ; <- UB @free_stack
  ret i32 0
}

; ASSERT UB 25: call i32 @free_stack()

define i32 @free_global() {
  call void @free(ptr @g)                         ; <- UB @free_global
  ret i32 0
}

; ASSERT UB 32: call i32 @free_global()

define i32 @free_interior() {
  %p = call ptr @malloc(i64 8)
  %q = getelementptr i8, ptr %p, i64 4
  call void @free(ptr %q)                         ; <- UB @free_interior
  ret i32 0
}

; ASSERT UB 41: call i32 @free_interior()

define i32 @free_poison(ptr %p) {
  call void @free(ptr %p)                         ; <- UB @free_poison
  ret i32 0
}

; ASSERT UB 48: call i32 @free_poison(ptr poison)

; Controls.
define i32 @free_null_ok() {
  call void @free(ptr null)
  ret i32 0
}

; ASSERT EQ: i32 0 = call i32 @free_null_ok()

; A null *address* is enough, whatever the provenance: `inttoptr i64 0` is the
; null pointer in address space 0 (LLVM's constant folder turns it into
; `null`), even though Vellvm gives it wildcard provenance.
define i32 @free_inttoptr_null_ok() {
  %p = inttoptr i64 0 to ptr
  call void @free(ptr %p)
  ret i32 0
}

; ASSERT EQ: i32 0 = call i32 @free_inttoptr_null_ok()

define i32 @malloc_free_ok() {
  %p = call ptr @malloc(i64 4)
  store i32 1, ptr %p
  call void @free(ptr %p)
  ret i32 0
}

; ASSERT EQ: i32 0 = call i32 @malloc_free_ok()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 21): ASSERT UB 17: call i32 @double_free()
define i32 @ub_case_0() {
  %r = call i32 @double_free()
  ret i32 %r
}

; case 1 (line 29): ASSERT UB 25: call i32 @free_stack()
define i32 @ub_case_1() {
  %r = call i32 @free_stack()
  ret i32 %r
}

; case 2 (line 36): ASSERT UB 32: call i32 @free_global()
define i32 @ub_case_2() {
  %r = call i32 @free_global()
  ret i32 %r
}

; case 3 (line 45): ASSERT UB 41: call i32 @free_interior()
define i32 @ub_case_3() {
  %r = call i32 @free_interior()
  ret i32 %r
}

; case 4 (line 52): ASSERT UB 48: call i32 @free_poison(ptr poison)
define i32 @ub_case_4() {
  %r = call i32 @free_poison(ptr poison)
  ret i32 %r
}

; case 5 (line 60): ASSERT EQ: i32 0 = call i32 @free_null_ok()
define i32 @ub_case_5() {
  %r = call i32 @free_null_ok()
  ret i32 %r
}

; case 6 (line 71): ASSERT EQ: i32 0 = call i32 @free_inttoptr_null_ok()
define i32 @ub_case_6() {
  %r = call i32 @free_inttoptr_null_ok()
  ret i32 %r
}

; case 7 (line 80): ASSERT EQ: i32 0 = call i32 @malloc_free_ok()
define i32 @ub_case_7() {
  %r = call i32 @malloc_free_ok()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
    i32 5, label %case5
    i32 6, label %case6
    i32 7, label %case7
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case5:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 5)
  %c5_r = call i32 @ub_case_5()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 5)
  %c5_0 = sext i32 %c5_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c5_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case6:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 6)
  %c6_r = call i32 @ub_case_6()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 6)
  %c6_0 = sext i32 %c6_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c6_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case7:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 7)
  %c7_r = call i32 @ub_case_7()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 7)
  %c7_0 = sext i32 %c7_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c7_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
