; UB tests for `llvm.assume` operand bundles.
;
; LangRef (Assume Operand Bundles): "Operand bundles on an llvm.assume allows
; representing assumptions ... If the provided guarantees are violated at
; runtime the behavior is undefined."  E.g. `"nonnull"(ptr %p)`,
; `"align"(ptr %p, i64 8)`, `"dereferenceable"(ptr %p, i64 4)`.

declare void @llvm.assume(i1 noundef)

define i32 @assume_nonnull(ptr %p) {
  call void @llvm.assume(i1 true) [ "nonnull"(ptr %p) ] ; <- UB @assume_nonnull
  ret i32 0
}

; ASSERT UB 11: call i32 @assume_nonnull(ptr null)

define i32 @assume_nonnull_ok() {
  %a = alloca i32
  %r = call i32 @assume_nonnull(ptr %a)
  ret i32 %r
}

; ASSERT EQ: i32 0 = call i32 @assume_nonnull_ok()

define i32 @assume_align() {
  %a = alloca [2 x i64], align 8
  %q = getelementptr i8, ptr %a, i64 4
  call void @llvm.assume(i1 true) [ "align"(ptr %q, i64 8) ] ; <- UB @assume_align
  ret i32 0
}

; ASSERT UB 28: call i32 @assume_align()

define i32 @assume_deref() {
  %a = alloca i16
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %a, i64 4) ] ; <- UB @assume_deref
  ret i32 0
}

; ASSERT UB 36: call i32 @assume_deref()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 15): ASSERT UB 11: call i32 @assume_nonnull(ptr null)
define i32 @ub_case_0() {
  %r = call i32 @assume_nonnull(ptr null)
  ret i32 %r
}

; case 1 (line 23): ASSERT EQ: i32 0 = call i32 @assume_nonnull_ok()
define i32 @ub_case_1() {
  %r = call i32 @assume_nonnull_ok()
  ret i32 %r
}

; case 2 (line 32): ASSERT UB 28: call i32 @assume_align()
define i32 @ub_case_2() {
  %r = call i32 @assume_align()
  ret i32 %r
}

; case 3 (line 40): ASSERT UB 36: call i32 @assume_deref()
define i32 @ub_case_3() {
  %r = call i32 @assume_deref()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
