; UB tests for the `llvm.assume` intrinsic.
;
; LangRef (llvm.assume, Semantics): "The intrinsic allows the optimizer to
; assume that the provided condition is always true whenever the control flow
; reaches the intrinsic call. ... If the condition is violated during
; execution, the behavior is undefined."
; A poison/undef condition is also UB: LLVM treats the argument as `noundef`
; (it is declared `i1 noundef` in Vellvm's libll/rust-intrinsics.ll, and
; LLVM's own intrinsic table gives it `NoUndef`).

declare void @llvm.assume(i1 noundef)

define i32 @assume(i1 %c) {
  call void @llvm.assume(i1 %c)                   ; <- UB @assume
  ret i32 0
}

; ASSERT UB 14: call i32 @assume(i1 0)
; ASSERT UB 14: call i32 @assume(i1 poison)
; ASSERT EQ: i32 0 = call i32 @assume(i1 1)

; The condition is usually computed.
define i32 @assume_nonzero(i32 %x) {
  %c = icmp ne i32 %x, 0
  call void @llvm.assume(i1 %c)                   ; <- UB @assume_nonzero
  ret i32 %x
}

; ASSERT UB 25: call i32 @assume_nonzero(i32 0)
; ASSERT EQ: i32 5 = call i32 @assume_nonzero(i32 5)

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 18): ASSERT UB 14: call i32 @assume(i1 0)
define i32 @ub_case_0() {
  %r = call i32 @assume(i1 0)
  ret i32 %r
}

; case 1 (line 19): ASSERT UB 14: call i32 @assume(i1 poison)
define i32 @ub_case_1() {
  %r = call i32 @assume(i1 poison)
  ret i32 %r
}

; case 2 (line 20): ASSERT EQ: i32 0 = call i32 @assume(i1 1)
define i32 @ub_case_2() {
  %r = call i32 @assume(i1 1)
  ret i32 %r
}

; case 3 (line 29): ASSERT UB 25: call i32 @assume_nonzero(i32 0)
define i32 @ub_case_3() {
  %r = call i32 @assume_nonzero(i32 0)
  ret i32 %r
}

; case 4 (line 30): ASSERT EQ: i32 5 = call i32 @assume_nonzero(i32 5)
define i32 @ub_case_4() {
  %r = call i32 @assume_nonzero(i32 5)
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
