; UB tests for the `llvm.memcpy.*` intrinsic.
;
; LangRef (llvm.memcpy, Semantics): "copy a block of memory from the source
; location to the destination location, which must either be equal or
; non-overlapping. ... If <len> is 0, it is no-op modulo the behavior of
; attributes attached to the arguments.  If <len> is not a well-defined value,
; the behavior is undefined.  If <len> is not zero, both <dest> and <src>
; should be well-defined, otherwise the behavior is undefined."
; The copy itself reads and writes memory, so the load/store rules (bounds,
; liveness, provenance, constant globals) apply as well.

declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
declare ptr @malloc(i64)
declare void @free(ptr)

@src = global [4 x i8] c"abcd"
@k = constant [4 x i8] c"wxyz"

define i32 @memcpy_len(i64 %n) {
  %d = alloca [4 x i8]
  call void @llvm.memcpy.p0.p0.i64(ptr %d, ptr @src, i64 %n, i1 false) ; <- UB @memcpy_len
  ret i32 0
}

; ASSERT UB 21: call i32 @memcpy_len(i64 poison)
; Copying past the end of either buffer.
; ASSERT UB 21: call i32 @memcpy_len(i64 5)
; ASSERT EQ: i32 0 = call i32 @memcpy_len(i64 4)

define i32 @memcpy_undef_len() {
  %d = alloca [4 x i8]
  call void @llvm.memcpy.p0.p0.i64(ptr %d, ptr @src, i64 undef, i1 false) ; <- UB @memcpy_undef_len
  ret i32 0
}

; ASSERT UB 32: call i32 @memcpy_undef_len()

define i32 @memcpy_ptrs(ptr %d, ptr %s) {
  call void @llvm.memcpy.p0.p0.i64(ptr %d, ptr %s, i64 1, i1 false) ; <- UB @memcpy_ptrs
  ret i32 0
}

; ASSERT UB 39: call i32 @memcpy_ptrs(ptr null, ptr null)
; ASSERT UB 39: call i32 @memcpy_ptrs(ptr poison, ptr poison)

; Control: with len 0, null or poison pointers are fine.
define i32 @memcpy_zero(ptr %d, ptr %s) {
  call void @llvm.memcpy.p0.p0.i64(ptr %d, ptr %s, i64 0, i1 false)
  ret i32 0
}

; ASSERT EQ: i32 0 = call i32 @memcpy_zero(ptr null, ptr null)
; ASSERT EQ: i32 0 = call i32 @memcpy_zero(ptr poison, ptr poison)

; Partially overlapping source and destination.
define i32 @memcpy_overlap() {
  %b = alloca [8 x i8]
  store [8 x i8] c"01234567", ptr %b
  %d = getelementptr i8, ptr %b, i64 2
  call void @llvm.memcpy.p0.p0.i64(ptr %d, ptr %b, i64 4, i1 false) ; <- UB @memcpy_overlap
  ret i32 0
}

; ASSERT UB 60: call i32 @memcpy_overlap()

; Control: exactly equal source and destination is allowed.
define i32 @memcpy_equal_ok() {
  %b = alloca [4 x i8]
  store [4 x i8] c"0123", ptr %b
  call void @llvm.memcpy.p0.p0.i64(ptr %b, ptr %b, i64 4, i1 false)
  %v = load i8, ptr %b
  %r = zext i8 %v to i32
  ret i32 %r
}

; ASSERT EQ: i32 48 = call i32 @memcpy_equal_ok()

; Control: adjacent (non-overlapping) ranges in one object.
define i32 @memcpy_adjacent_ok() {
  %b = alloca [8 x i8]
  store [8 x i8] c"01234567", ptr %b
  %d = getelementptr i8, ptr %b, i64 4
  call void @llvm.memcpy.p0.p0.i64(ptr %d, ptr %b, i64 4, i1 false)
  %v = load i8, ptr %d
  %r = zext i8 %v to i32
  ret i32 %r
}

; ASSERT EQ: i32 48 = call i32 @memcpy_adjacent_ok()

; Destination freed.
define i32 @memcpy_dest_freed() {
  %d = call ptr @malloc(i64 4)
  call void @free(ptr %d)
  call void @llvm.memcpy.p0.p0.i64(ptr %d, ptr @src, i64 4, i1 false) ; <- UB @memcpy_dest_freed
  ret i32 0
}

; ASSERT UB 95: call i32 @memcpy_dest_freed()

; Destination is a constant global.
define i32 @memcpy_to_constant() {
  call void @llvm.memcpy.p0.p0.i64(ptr @k, ptr @src, i64 4, i1 false) ; <- UB @memcpy_to_constant
  ret i32 0
}

; ASSERT UB 103: call i32 @memcpy_to_constant()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 25): ASSERT UB 21: call i32 @memcpy_len(i64 poison)
define i32 @ub_case_0() {
  %r = call i32 @memcpy_len(i64 poison)
  ret i32 %r
}

; case 1 (line 27): ASSERT UB 21: call i32 @memcpy_len(i64 5)
define i32 @ub_case_1() {
  %r = call i32 @memcpy_len(i64 5)
  ret i32 %r
}

; case 2 (line 28): ASSERT EQ: i32 0 = call i32 @memcpy_len(i64 4)
define i32 @ub_case_2() {
  %r = call i32 @memcpy_len(i64 4)
  ret i32 %r
}

; case 3 (line 36): ASSERT UB 32: call i32 @memcpy_undef_len()
define i32 @ub_case_3() {
  %r = call i32 @memcpy_undef_len()
  ret i32 %r
}

; case 4 (line 43): ASSERT UB 39: call i32 @memcpy_ptrs(ptr null, ptr null)
define i32 @ub_case_4() {
  %r = call i32 @memcpy_ptrs(ptr null, ptr null)
  ret i32 %r
}

; case 5 (line 44): ASSERT UB 39: call i32 @memcpy_ptrs(ptr poison, ptr poison)
define i32 @ub_case_5() {
  %r = call i32 @memcpy_ptrs(ptr poison, ptr poison)
  ret i32 %r
}

; case 6 (line 52): ASSERT EQ: i32 0 = call i32 @memcpy_zero(ptr null, ptr null)
define i32 @ub_case_6() {
  %r = call i32 @memcpy_zero(ptr null, ptr null)
  ret i32 %r
}

; case 7 (line 53): ASSERT EQ: i32 0 = call i32 @memcpy_zero(ptr poison, ptr poison)
define i32 @ub_case_7() {
  %r = call i32 @memcpy_zero(ptr poison, ptr poison)
  ret i32 %r
}

; case 8 (line 64): ASSERT UB 60: call i32 @memcpy_overlap()
define i32 @ub_case_8() {
  %r = call i32 @memcpy_overlap()
  ret i32 %r
}

; case 9 (line 76): ASSERT EQ: i32 48 = call i32 @memcpy_equal_ok()
define i32 @ub_case_9() {
  %r = call i32 @memcpy_equal_ok()
  ret i32 %r
}

; case 10 (line 89): ASSERT EQ: i32 48 = call i32 @memcpy_adjacent_ok()
define i32 @ub_case_10() {
  %r = call i32 @memcpy_adjacent_ok()
  ret i32 %r
}

; case 11 (line 99): ASSERT UB 95: call i32 @memcpy_dest_freed()
define i32 @ub_case_11() {
  %r = call i32 @memcpy_dest_freed()
  ret i32 %r
}

; case 12 (line 107): ASSERT UB 103: call i32 @memcpy_to_constant()
define i32 @ub_case_12() {
  %r = call i32 @memcpy_to_constant()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
    i32 5, label %case5
    i32 6, label %case6
    i32 7, label %case7
    i32 8, label %case8
    i32 9, label %case9
    i32 10, label %case10
    i32 11, label %case11
    i32 12, label %case12
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case5:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 5)
  %c5_r = call i32 @ub_case_5()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 5)
  %c5_0 = sext i32 %c5_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c5_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case6:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 6)
  %c6_r = call i32 @ub_case_6()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 6)
  %c6_0 = sext i32 %c6_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c6_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case7:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 7)
  %c7_r = call i32 @ub_case_7()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 7)
  %c7_0 = sext i32 %c7_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c7_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case8:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 8)
  %c8_r = call i32 @ub_case_8()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 8)
  %c8_0 = sext i32 %c8_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c8_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case9:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 9)
  %c9_r = call i32 @ub_case_9()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 9)
  %c9_0 = sext i32 %c9_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c9_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case10:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 10)
  %c10_r = call i32 @ub_case_10()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 10)
  %c10_0 = sext i32 %c10_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c10_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case11:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 11)
  %c11_r = call i32 @ub_case_11()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 11)
  %c11_0 = sext i32 %c11_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c11_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case12:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 12)
  %c12_r = call i32 @ub_case_12()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 12)
  %c12_0 = sext i32 %c12_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c12_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
