; UB tests for the `llvm.memset.*` intrinsic.
;
; LangRef (llvm.memset, Semantics): "If <len> is 0, it is no-op modulo the
; behavior of attributes attached to the arguments.  If <len> is not a
; well-defined value, the behavior is undefined.  If <len> is not zero, <dest>
; should be well-defined, otherwise the behavior is undefined."
; The fill itself writes memory, so the store rules apply.

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)

@k = constant [4 x i8] c"wxyz"

define i32 @memset_len(i64 %n) {
  %d = alloca [4 x i8]
  call void @llvm.memset.p0.i64(ptr %d, i8 0, i64 %n, i1 false) ; <- UB @memset_len
  ret i32 0
}

; ASSERT UB 15: call i32 @memset_len(i64 poison)
; ASSERT UB 15: call i32 @memset_len(i64 5)
; ASSERT EQ: i32 0 = call i32 @memset_len(i64 4)

define i32 @memset_undef_len() {
  %d = alloca [4 x i8]
  call void @llvm.memset.p0.i64(ptr %d, i8 0, i64 undef, i1 false) ; <- UB @memset_undef_len
  ret i32 0
}

; ASSERT UB 25: call i32 @memset_undef_len()

define i32 @memset_dest(ptr %d) {
  call void @llvm.memset.p0.i64(ptr %d, i8 0, i64 1, i1 false) ; <- UB @memset_dest
  ret i32 0
}

; ASSERT UB 32: call i32 @memset_dest(ptr null)
; ASSERT UB 32: call i32 @memset_dest(ptr poison)

define i32 @memset_zero(ptr %d) {
  call void @llvm.memset.p0.i64(ptr %d, i8 0, i64 0, i1 false)
  ret i32 0
}

; ASSERT EQ: i32 0 = call i32 @memset_zero(ptr null)
; ASSERT EQ: i32 0 = call i32 @memset_zero(ptr poison)

; Control: a poison fill *value* is not UB; it stores poison bytes.
define i32 @memset_poison_value_ok() {
  %d = alloca i8
  call void @llvm.memset.p0.i64(ptr %d, i8 poison, i64 1, i1 false)
  %v = load i8, ptr %d
  %r = zext i8 %v to i32
  ret i32 %r
}

; ASSERT EQ: i32 poison = call i32 @memset_poison_value_ok()

define i32 @memset_constant() {
  call void @llvm.memset.p0.i64(ptr @k, i8 0, i64 4, i1 false) ; <- UB @memset_constant
  ret i32 0
}

; ASSERT UB 59: call i32 @memset_constant()

; ---- BEGIN executable tail generated by tests/gen.py --dispatch (do not edit) ----
; `main N` runs case N alone, so UB in one case cannot mask another;
; @ub_case_N is an argument-free entry point for the same call.

; case 0 (line 19): ASSERT UB 15: call i32 @memset_len(i64 poison)
define i32 @ub_case_0() {
  %r = call i32 @memset_len(i64 poison)
  ret i32 %r
}

; case 1 (line 20): ASSERT UB 15: call i32 @memset_len(i64 5)
define i32 @ub_case_1() {
  %r = call i32 @memset_len(i64 5)
  ret i32 %r
}

; case 2 (line 21): ASSERT EQ: i32 0 = call i32 @memset_len(i64 4)
define i32 @ub_case_2() {
  %r = call i32 @memset_len(i64 4)
  ret i32 %r
}

; case 3 (line 29): ASSERT UB 25: call i32 @memset_undef_len()
define i32 @ub_case_3() {
  %r = call i32 @memset_undef_len()
  ret i32 %r
}

; case 4 (line 36): ASSERT UB 32: call i32 @memset_dest(ptr null)
define i32 @ub_case_4() {
  %r = call i32 @memset_dest(ptr null)
  ret i32 %r
}

; case 5 (line 37): ASSERT UB 32: call i32 @memset_dest(ptr poison)
define i32 @ub_case_5() {
  %r = call i32 @memset_dest(ptr poison)
  ret i32 %r
}

; case 6 (line 44): ASSERT EQ: i32 0 = call i32 @memset_zero(ptr null)
define i32 @ub_case_6() {
  %r = call i32 @memset_zero(ptr null)
  ret i32 %r
}

; case 7 (line 45): ASSERT EQ: i32 0 = call i32 @memset_zero(ptr poison)
define i32 @ub_case_7() {
  %r = call i32 @memset_zero(ptr poison)
  ret i32 %r
}

; case 8 (line 56): ASSERT EQ: i32 poison = call i32 @memset_poison_value_ok()
define i32 @ub_case_8() {
  %r = call i32 @memset_poison_value_ok()
  ret i32 %r
}

; case 9 (line 63): ASSERT UB 59: call i32 @memset_constant()
define i32 @ub_case_9() {
  %r = call i32 @memset_constant()
  ret i32 %r
}

@ub_fmt_start = private unnamed_addr constant [16 x i8] c"case %d: start\0A\00"
@ub_fmt_ret = private unnamed_addr constant [18 x i8] c"case %d: returned\00"
@ub_fmt_int = private unnamed_addr constant [6 x i8] c" %lld\00"
@ub_fmt_fp = private unnamed_addr constant [4 x i8] c" %g\00"
@ub_fmt_nl = private unnamed_addr constant [2 x i8] c"\0A\00"

declare i32 @printf(ptr, ...)
declare i32 @atoi(ptr)

define i32 @main(i32 %argc, ptr %argv) {
entry:
  %has_arg = icmp sge i32 %argc, 2
  br i1 %has_arg, label %dispatch, label %bad
dispatch:
  %arg1_p = getelementptr ptr, ptr %argv, i64 1
  %arg1 = load ptr, ptr %arg1_p
  %n = call i32 @atoi(ptr %arg1)
  switch i32 %n, label %bad [
    i32 0, label %case0
    i32 1, label %case1
    i32 2, label %case2
    i32 3, label %case3
    i32 4, label %case4
    i32 5, label %case5
    i32 6, label %case6
    i32 7, label %case7
    i32 8, label %case8
    i32 9, label %case9
  ]
case0:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 0)
  %c0_r = call i32 @ub_case_0()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 0)
  %c0_0 = sext i32 %c0_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c0_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case1:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 1)
  %c1_r = call i32 @ub_case_1()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 1)
  %c1_0 = sext i32 %c1_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c1_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case2:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 2)
  %c2_r = call i32 @ub_case_2()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 2)
  %c2_0 = sext i32 %c2_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c2_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case3:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 3)
  %c3_r = call i32 @ub_case_3()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 3)
  %c3_0 = sext i32 %c3_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c3_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case4:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 4)
  %c4_r = call i32 @ub_case_4()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 4)
  %c4_0 = sext i32 %c4_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c4_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case5:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 5)
  %c5_r = call i32 @ub_case_5()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 5)
  %c5_0 = sext i32 %c5_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c5_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case6:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 6)
  %c6_r = call i32 @ub_case_6()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 6)
  %c6_0 = sext i32 %c6_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c6_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case7:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 7)
  %c7_r = call i32 @ub_case_7()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 7)
  %c7_0 = sext i32 %c7_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c7_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case8:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 8)
  %c8_r = call i32 @ub_case_8()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 8)
  %c8_0 = sext i32 %c8_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c8_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
case9:
  call i32 (ptr, ...) @printf(ptr @ub_fmt_start, i32 9)
  %c9_r = call i32 @ub_case_9()
  call i32 (ptr, ...) @printf(ptr @ub_fmt_ret, i32 9)
  %c9_0 = sext i32 %c9_r to i64
  call i32 (ptr, ...) @printf(ptr @ub_fmt_int, i64 %c9_0)
  call i32 (ptr, ...) @printf(ptr @ub_fmt_nl)
  ret i32 0
bad:
  ret i32 2
}
; ---- END executable tail ----
