From Vellvm Require Import
     Semantics.LLVMParams
     Semantics.MemoryParams
     Semantics.Memory.MemBytes
     Handlers.Concretization
     Handlers.MemoryModel.

(* SAZ: MODULE CLEANUP TODO: The module Conc has a huge signature, including obligations
    generated by [Program Fixpoint].  Figure out how to do this differently. 
 *)
(*  
Module Type _CONCRETIZATION_PARAMS (LP : PARAMS) (MMSP : MemoryModelSpecPrimitives_SERIALIZE LP).
  Include (Concretization.CONCRETIZATION LP MMSP).
End _CONCRETIZATION_PARAMS.

Module Type CONCRETIZATION_PARAMS (LP : PARAMS) := (MMME LP) <+ (_CONCRETIZATION_PARAMS LP).

Module Make (LP : PARAMS) (M : MMME LP) : CONCRETIZATION_PARAMS LP.
  Include M.
  Include (Concretization.Make LP M).
End Make.
*)

