name: Hugo Web Pages Build and Deploy
on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
    paths:
      - docs/**

  # Allows you to run this workflow manually from the Actions tab      
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages    
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.  
concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site from /docs
        run: |
          hugo --source=docs --destination=public

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
