name: Vellvm Compilation Test

on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'web/**'
  push:
    branches:
      - dev
    paths-ignore:
      - 'web/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
        coq_version:
          - "9.1"
        ocaml_version:
          - "4.14-flambda"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compiling Vellvm
        uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'rocq-vellvm.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          before_install: |
            startGroup "Set stack limits"
              ulimit -s; ulimit -s unlimited; ulimit -s
            endGroup
            startGroup "Print opam config"
              opam config list; opam repo list; opam list
            endGroup
